### ISSUE TITLE
link formatting

### ISSUE THREAD

**Issue by stefan-korn** [virtualidentityag/stadtKoeln-openData-frontend#28]
What is the meaning behind the `link` class formatting: https://github.com/virtualidentityag/stadtKoeln-openData-frontend/blob/main/src/styles/components/_link.scss#L15

`link` class is not a bootstrap default class as far as I can tell and the resulting styling for a link with `link` class seems to be the same as if the `btn-link` class is used.

So imho the `link` class formatting is not necessary and any link using this class can be reformatted to use `btn-link` class instead. Any link formatting that should affect basic links (a tag) should be placed under styles for the a tag.
That said the links in the text for the blog page all get the bootstrap `fw-semibold` class. Is this meant as a default for any basic link? If so, this should rather be placed in scss for the a tag, because we cannot easily ensure that every basic link out of Drupal receives this class.

Also on the blog page the font-size and line height for the text is set by `fs-4` and `lh-sm`. Should this be considered default style for all basic texts? Than it might be better to apply this at body level and only override execptions.

**Comment by paulovareiro29** [comment]
PRs have been merged.
Will proceed to close the issue.
