### ISSUE TITLE
Home - Extended Categories

### ISSUE THREAD

**Issue by stefan-korn** [virtualidentityag/stadtKoeln-openData-frontend#38]
If we really want to go with the feature of "extending" categories on the homepage, we would need some kind of toggle solution.

This toggle solution should be provided within this repo then.

I am bit reluctant on the current approach to hide categories based on viewport. This would probably make a toggle solution more difficult. In the current approach of extended categories (which maybe is only a "mockup") it just cuts off some categories in smaller viewports, which surely is no viable solution.

From my perspective we would not absolutely need the "extending" feature, so just displaying all categories in multiple rows would be acceptable for me too. This is maybe something we can discuss during next weekly @koepferd ?
Since this is actually tied to a [controlled EU vocabulary](https://op.europa.eu/de/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/data-theme), the maximum number of categories is currently 13. The vocabulary maybe extended in the future, but hasn't since 2015, so probably it might stay the same.

And it would be better from Drupal perspective to use [bootstrap row columns](https://getbootstrap.com/docs/5.3/layout/grid/#row-columns) on this.

@koepferd : Something off-topic: Could you maybe add https://github.com/DKANCologneServiceOwner to this repo, so we can mention on some issues?

**Comment by koepferd** [comment]
Hi @stefan-korn,
we discussed this yesterday. 
From UX perspective we will keep this functionality. @paulovareiro29 will implement the toggle solution.

Also I invited this DKAN user to the repository, they should check their invites.
