### ISSUE TITLE
Data Enquiry - "Öffentliche Datenanfragen"

### ISSUE THREAD

**Issue by stefan-korn** [virtualidentityag/stadtKoeln-openData-frontend#42]
[Data enquiry](https://virtualidentityag.github.io/stadtKoeln-openData-frontend/main/enquiry) has an image/text teaser.

It should be decided if we really need this and if so, what it should contain.

Currently content looks like a "quote", but also a "Weiterlesen" (read more) link is indicated. Looks a bit like a "filler" only ...

**Comment by koepferd** [comment]
That "Weiterlesen" doesn't need functionality and will be removed. Thanks for the hint.
