### ISSUE TITLE
Avoid dark-mode-only/light-mode-only for formats/icon display in dataset overview

### ISSUE THREAD

**Issue by stefan-korn** [virtualidentityag/stadtKoeln-openData-frontend#43]
We would like to avoid the duplicate output of the formats and icons for light/dark mode on the dataset overview page.

PR will follow

**Comment by stefan-korn** [comment]
and the gap between the format badges is currently only introduced by whitespace between the formats. This is not reliable enough, introduce a flex-gap for this. see PR #44

**Comment by paulovareiro29** [comment]
Closed by #44
